name: Build Windows DLL

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - uses: actions/upload-artifact@v3
        with:
          name: aclog-dll
          path: build/**/*.dll
